// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emffdnkdbtpyiiaddyqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZmZkbmtkYnRweWlpYWRkeXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDU5NzcsImV4cCI6MjA2MjA4MTk3N30.D64J-Ej3Cax9SNpzHeEwiH8Jnewu3boS5V2bEyoVlIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);